services:
  # Основне API додаток
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongo:27017/parser_db?authSource=admin
      - DATABASE_NAME=parser_db
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - parser_network

  # MongoDB база даних
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=parser_db
    volumes:
      - mongo_data:/data/db
      - mongo-config:/data/configdb
    networks:
      - parser_network

  # MongoDB Express (веб-інтерфейс для MongoDB)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongo:27017/
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - parser_network

volumes:
  mongo_data:
    driver: local
  mongo-config:
    driver: local
networks:
  parser_network:
    driver: bridge